"""Beast M1 fan-out — SSH to Beast, run M1Orchestrator, return raw results.

Renders a self-contained Python script from the anchor list, copies it into
the research-pipe container, runs it, and returns structured JSON.

Pattern: Cursor's proven /tmp/beast_rerun.py approach — one script, one SSH
call, stdout is JSON. No persistent state in /tmp; script is idempotent.

Signed-by: cascade-mac | 2026-06-27 | cman-research-pipe
"""
from __future__ import annotations

import json
import subprocess
import textwrap
import time
from pathlib import Path

BEAST_HOST    = "beast"
CONTAINER     = "research-pipe"
REMOTE_SCRIPT = "/tmp/beast_cman_fanout.py"


def _render_script(anchors: list[dict], run_id: str) -> str:
    queries_repr = repr([a["query"] for a in anchors])
    return textwrap.dedent(f"""\
        \"\"\"Beast CMAN fan-out — auto-generated by cascade-mac cman_pipe.\"\"\"
        import asyncio, json, os
        from datetime import datetime, timezone
        from epistemic_core.tiers import EpistemicTier
        from research_pipe.backends.searxng import SearXNGBackend
        from research_pipe.emitter import LogEmitter
        from research_pipe.orchestrators.m1 import M1Orchestrator
        from research_pipe.promotion_alert import AlertQueue, alert_from_drift
        from research_pipe.promotion_investigation import process_queue
        from research_pipe.query_schema import BackendLayer, ResearchQuery, SearchMode, SearchType
        from research_pipe.router import BackendRouter
        from research_pipe.vellum_signer import VellumSigner

        RUN_ID   = {run_id!r}
        BRAIN_ID = RUN_ID
        QUERIES  = {queries_repr}

        async def fan_out(orch):
            probes, all_results = [], []
            for i, q in enumerate(QUERIES, 1):
                query = ResearchQuery(
                    mode=SearchMode.M1,
                    brain_entry_id=BRAIN_ID,
                    sharpened_question=q,
                    query_string=q,
                    search_type=SearchType.M1,
                    backend_set=[BackendLayer.L1],
                    local_attempts_count=2,
                    five_rods_result="verify:radical_honesty:research_proposes_python_disposes",
                    pudding_label=f"{{RUN_ID}}.wide1",
                )
                run = await orch.execute(query)
                results = run.search_run.results if run.search_run else []
                hits = len(results)
                for r in results:
                    all_results.append({{
                        "title":   r.title,
                        "url":     r.url,
                        "snippet": r.snippet or "",
                        "domain":  QUERIES[i-1][:30],
                        "probe":   i,
                    }})
                probes.append({{"probe": i, "query": q[:80], "hits": hits,
                                "success": run.success, "error": run.error}})
            return probes, all_results

        async def main():
            router = BackendRouter()
            router.register(BackendLayer.L1, SearXNGBackend())
            orch = M1Orchestrator(
                router=router,
                signer=VellumSigner(agent_id="cascade-mac-cman"),
                emitter=LogEmitter(),
            )
            probes, all_results = await fan_out(orch)
            claim = f"CMAN fan-out {{len(probes)}} probes {{len(all_results)}} results — INTUITED."
            alert = alert_from_drift(
                brain_entry_id=BRAIN_ID, claim=claim,
                current_tier=EpistemicTier.INTUITED, drift_signal="green",
                reason=f"cascade-mac CMAN {{RUN_ID}}",
                pudding_label=f"{{RUN_ID}}.swanson",
            )
            path = AlertQueue().enqueue(alert)
            inv_results = await process_queue(limit=1)
            inv = inv_results[0] if inv_results else None
            print(json.dumps({{
                "run_id": RUN_ID,
                "timestamp": datetime.now(timezone.utc).isoformat(),
                "searxng_url": os.environ.get("SEARXNG_URL"),
                "probes": probes,
                "total_hits": len(all_results),
                "results": all_results,
                "batch_id": inv.batch_id if inv else None,
                "gate0_passed": inv.gate0_passed if inv else 0,
                "gate0_failed": inv.gate0_failed if inv else 0,
            }}))

        asyncio.run(main())
    """)


def run(anchors: list[dict], run_id: str, *, timeout: int = 180) -> dict:
    """Run CMAN fan-out on Beast. Returns parsed JSON output."""
    script = _render_script(anchors, run_id)

    # Write to local /tmp, scp to Beast host, cp into container, execute
    local_tmp = Path(f"/tmp/beast_cman_fanout_{int(time.time())}.py")
    local_tmp.write_text(script)

    try:
        # scp to Beast host /tmp
        subprocess.run(
            ["scp", "-q", str(local_tmp), f"{BEAST_HOST}:{REMOTE_SCRIPT}"],
            check=True, timeout=30,
        )
        # cp into container and run
        proc = subprocess.run(
            ["ssh", BEAST_HOST,
             f"docker cp {REMOTE_SCRIPT} {CONTAINER}:{REMOTE_SCRIPT} && "
             f"docker exec {CONTAINER} python3 {REMOTE_SCRIPT}"],
            capture_output=True, text=True, timeout=timeout,
        )
        if proc.returncode != 0:
            return {"error": proc.stderr[-800:] or "non-zero exit", "results": []}
        # Last line is the JSON (LogEmitter may print other lines)
        lines = [l for l in proc.stdout.strip().splitlines() if l.strip()]
        for line in reversed(lines):
            try:
                return json.loads(line)
            except json.JSONDecodeError:
                continue
        return {"error": "no JSON in output", "raw": proc.stdout[:400], "results": []}
    finally:
        local_tmp.unlink(missing_ok=True)
