#!/usr/bin/env python3
"""Sync Hooks and Harnesses to Cursor Rules.

Scans the central harnesses folder and its hooks subdirectory, parses metadata,
generates a unified Cursor rule file `.cursor/rules/active-harnesses.mdc`,
propagates it to the main workspace and active worktrees, and logs the sync action to Vellum.
"""
import os
import sys
import ast
import ssl
import json
import uuid
import urllib.request
from datetime import datetime, timezone, timedelta
from pathlib import Path

# Paths
HARNESS_DIR = Path(__file__).resolve().parent
ROOT_DIR = HARNESS_DIR.parent.parent  # /Users/ewansair/ingestion-to-research-pipe
VELLUM_URL = "https://vellum.beast.amplifiedpartners.ai"
VELLUM_JWT_SECRET = "vellum-dogfood-2026-scaffold"

try:
    import jwt
except ImportError:
    jwt = None


def extract_metadata(file_path: Path) -> dict:
    """Parses a Python file using AST and extracts module, class, and function docstrings."""
    try:
        content = file_path.read_text()
        tree = ast.parse(content, filename=str(file_path))
    except Exception as e:
        return {"error": f"Failed to parse file: {e}"}

    docstring = ast.get_docstring(tree) or ""
    metadata = {
        "docstring": docstring.strip(),
        "classes": [],
        "functions": []
    }

    for node in tree.body:
        if isinstance(node, ast.ClassDef):
            class_doc = ast.get_docstring(node) or ""
            class_meta = {
                "name": node.name,
                "docstring": class_doc.strip(),
                "methods": []
            }
            for subnode in node.body:
                if isinstance(subnode, ast.FunctionDef):
                    # Skip private/dunder methods unless they are __init__
                    if subnode.name.startswith("_") and subnode.name != "__init__":
                        continue
                    method_doc = ast.get_docstring(subnode) or ""
                    
                    # Construct arg list
                    args = []
                    for arg in subnode.args.args:
                        args.append(arg.arg)
                    sig = f"def {subnode.name}({', '.join(args)})"
                    
                    class_meta["methods"].append({
                        "name": subnode.name,
                        "signature": sig,
                        "docstring": method_doc.strip()
                    })
            metadata["classes"].append(class_meta)
            
        elif isinstance(node, ast.FunctionDef):
            if node.name.startswith("_"):
                continue
            func_doc = ast.get_docstring(node) or ""
            
            args = []
            for arg in node.args.args:
                args.append(arg.arg)
            sig = f"def {node.name}({', '.join(args)})"
            
            metadata["functions"].append({
                "name": node.name,
                "signature": sig,
                "docstring": func_doc.strip()
            })

    return metadata


def generate_markdown(all_metadata: dict) -> str:
    """Assembles MDC rule file content with frontmatter and structured metadata."""
    md = [
        "---",
        "description: SSOT of all active validation harnesses, hooks, and gatekeepers to ensure agent execution is deterministic, database targets are correct, and code commits conform.",
        "globs: *",
        "alwaysApply: true",
        "---",
        "",
        "# Active Harnesses & Validation Gates",
        "",
        "This document is automatically generated by `sync_hooks_to_rules.py` from active python harnesses and hooks. Do not edit this file directly.",
        "",
    ]

    for file_rel, meta in sorted(all_metadata.items()):
        md.append(f"## `{file_rel}`")
        if meta.get("error"):
            md.append(f"**Error parsing**: {meta['error']}")
            md.append("")
            continue

        if meta.get("docstring"):
            md.append(meta["docstring"])
            md.append("")

        if meta.get("classes"):
            for cls in meta["classes"]:
                md.append(f"### `class {cls['name']}`")
                if cls.get("docstring"):
                    md.append(cls["docstring"])
                    md.append("")
                if cls.get("methods"):
                    md.append("#### Methods:")
                    for method in cls["methods"]:
                        md.append(f"- `{method['signature']}`")
                        if method.get("docstring"):
                            indented = "\n".join("  " + l for l in method["docstring"].splitlines())
                            md.append(indented)
                    md.append("")
            md.append("")

        if meta.get("functions"):
            md.append("### Functions")
            for func in meta["functions"]:
                md.append(f"- `{func['signature']}`")
                if func.get("docstring"):
                    indented = "\n".join("  " + l for l in func["docstring"].splitlines())
                    md.append(indented)
            md.append("")
        
        md.append("---")
        md.append("")

    return "\n".join(md)


def make_token(sheet_id: str, role: str = "write") -> str:
    """Generates the Vellum JWT token if PyJWT is available."""
    if not jwt:
        raise RuntimeError("PyJWT ('jwt') library is missing. Cannot sign token.")
    return jwt.encode(
        {
            "jti": str(uuid.uuid4()),
            "sub": "mcp-agent",
            "sheet_id": sheet_id,
            "role": role,
            "iat": datetime.now(timezone.utc),
            "exp": datetime.now(timezone.utc) + timedelta(hours=24),
        },
        VELLUM_JWT_SECRET,
        algorithm="HS256",
    )


def api_post(path: str, body: dict, token: str = None) -> dict:
    """Sends a POST request to Vellum API."""
    data = json.dumps(body).encode()
    headers = {"Content-Type": "application/json"}
    if token:
        headers["Authorization"] = f"Bearer {token}"
    req = urllib.request.Request(
        f"{VELLUM_URL}{path}",
        data=data,
        headers=headers,
        method="POST"
    )
    context = ssl._create_unverified_context()
    with urllib.request.urlopen(req, timeout=10, context=context) as resp:
        return json.loads(resp.read().decode())


def main():
    print("Scanning active harnesses and hooks...")
    all_metadata = {}

    # Scan perplexity-inbox/harness/
    for item in HARNESS_DIR.iterdir():
        if item.is_file() and item.suffix == ".py":
            # skip sync_hooks_to_rules.py itself to avoid self-referential clutter
            if item.name == "sync_hooks_to_rules.py":
                continue
            rel_path = f"perplexity-inbox/harness/{item.name}"
            all_metadata[rel_path] = extract_metadata(item)

    # Scan perplexity-inbox/harness/hooks/
    hooks_dir = HARNESS_DIR / "hooks"
    if hooks_dir.is_dir():
        for item in hooks_dir.iterdir():
            if item.is_file() and item.suffix == ".py":
                rel_path = f"perplexity-inbox/harness/hooks/{item.name}"
                all_metadata[rel_path] = extract_metadata(item)

    print(f"Extracted metadata from {len(all_metadata)} scripts.")

    # Generate Markdown Cursor Rule
    mdc_content = generate_markdown(all_metadata)

    # Propagate to Main Workspace
    main_rules_dir = ROOT_DIR / ".cursor" / "rules"
    main_rules_dir.mkdir(parents=True, exist_ok=True)
    main_file = main_rules_dir / "active-harnesses.mdc"
    main_file.write_text(mdc_content)
    print(f"Successfully generated main rule file at: {main_file}")

    # Propagate to Worktrees
    worktrees_dir = ROOT_DIR / ".worktrees"
    wt_count = 0
    if worktrees_dir.is_dir():
        for item in worktrees_dir.iterdir():
            if item.is_dir() and not item.name.startswith("."):
                wt_rules_dir = item / ".cursor" / "rules"
                
                # Handle symlinks (like broken /Volumes symlinks)
                if wt_rules_dir.is_symlink():
                    try:
                        resolved = wt_rules_dir.resolve(strict=True)
                        if resolved.is_dir():
                            wt_file = resolved / "active-harnesses.mdc"
                            wt_file.write_text(mdc_content)
                            wt_count += 1
                            print(f"Propagated rule file to resolved symlink: {wt_file}")
                            continue
                    except (FileNotFoundError, OSError):
                        print(f"Skipping broken or unresolvable symlink in worktree: {wt_rules_dir}")
                        continue
                
                try:
                    wt_rules_dir.mkdir(parents=True, exist_ok=True)
                    wt_file = wt_rules_dir / "active-harnesses.mdc"
                    wt_file.write_text(mdc_content)
                    wt_count += 1
                    print(f"Propagated rule file to worktree: {wt_file}")
                except Exception as e:
                    print(f"Failed to write to worktree {item.name}: {e}")
    print(f"Propagated rules file to {wt_count} active worktrees.")

    # Log to Vellum
    if not jwt:
        print("WARNING: 'jwt' library not installed. Skipping Vellum logging.", file=sys.stderr)
        return

    print("Posting update to Vellum estate log...")
    try:
        token = make_token("estate-status", "write")
        payload = {
            "author": "antigravity",
            "content": f"Deterministic sync pipeline updated `.cursor/rules/active-harnesses.mdc` across {wt_count + 1} environments based on active harnesses/hooks metadata.",
            "metadata": {
                "repo": "ingestion-to-research-pipe",
                "action": "sync-hooks-to-rules",
                "pr": "none"
            }
        }
        res = api_post("/api/v1/estate/log", payload, token)
        print("Vellum sync logged successfully:", res)
    except Exception as e:
        print(f"Failed to post sync update to Vellum: {e}", file=sys.stderr)


if __name__ == "__main__":
    main()
